# https://help.github.com/en/actions

# https://github.com/actions
# https://github.com/actions/checkout
# https://github.com/actions/setup-node

# No Arm Linux tests yet.

# https://nodejs.org/en/download/releases/

name: Node.js CI on Push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - '**.md'
      - '.gitignore'
      - '.npmignore'
      - '.vscode/**'
      - 'README*'
      - 'NOTES.md'
      - 'CHANGELOG.md'


jobs:
  npm-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # nvm ls-remote --lts
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ ubuntu-22.04, windows-2022, macos-12 ]
        # https://github.com/actions/setup-node
        node-version: [ 16, 18, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Show node & npm versions, environment
        run: |
          node --version
          npm --version
          env
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
